/// Flutter icons Front
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Front
///      fonts:
///       - asset: fonts/Front.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class Front {
  Front._();

  static const _kFontFam = 'Front';
  static const String? _kFontPkg = null;

  static const IconData work = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graduation_hat = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
